# Set up the global variables

In [1]:
BASE_DIR = '/kaggle/input/competitions/textual-analysis-in-finance-mid-term-assignment'

# Load the data

In [2]:
import os
import pandas as pd

train_data = pd.read_csv(os.path.join(BASE_DIR, 'train.csv'))
display(train_data.head())

test_data = pd.read_csv(os.path.join(BASE_DIR, 'test.csv'))
display(test_data.head())

,para_idx,cik,ddate,form,para,is_hedge
0,573e92be-f,1750,20101130,10-Q,"Note 9 Acquisitions On April 7, 2010, we acqu...",0
1,b6d3abd7-4,1750,20110831,10-Q,Note 7 Derivative Instruments and Hedging Act...,1
2,d35393df-f,1750,20111130,10-Q,Note 1 Basis of Presentation AAR CORP. and it...,0
3,9fae95e7-1,1750,20111130,10-Q,Note 8 Derivative Instruments and Hedging Act...,1
4,8f86367b-7,1750,20120229,10-Q,Year Lease Expiration Post-Lease Quantity Airc...,0

,para_idx,cik,ddate,form,para
0,f7dd28e9-a,1750,20160229,10-Q,Note 10 Derivative Instruments and Hedging Ac...
1,501a120a-9,1750,20160531,10-K,"May 31, 2016 2015 Revolving Credit Facility ex..."
2,0b5831ea-e,1750,20160531,10-K,Equipment under Leases Lease revenue is recogn...
3,7734186b-3,1750,20160531,10-K,4. Derivative Instruments and Hedging Activiti...
4,134b31b7-8,1750,20160831,10-Q,Currency Translation Adjustments Pension Plans...

# Modeling

I simply predict that everything is **not a hedging paragraph**

This is where you write your model

In [3]:
test_data['is_hedge'] = 0

# Submission

This is where you prepare a submission, so, you **MUST KEEP EVERYTHING UNCHANGED**!

In [4]:
submission = test_data[['para_idx', 'is_hedge']]
submission.to_csv('submission.csv', index = None)
submission.head()

     para_idx  is_hedge
0  f7dd28e9-a         0
1  501a120a-9         0
2  0b5831ea-e         0
3  7734186b-3         0
4  134b31b7-8         0